### ISSUE TITLE
Cannot build the ndk immediately after cloning the repo

### ISSUE THREAD

**Issue by maltzj** [bugsnag/bugsnag-android-ndk#8]
### Expected behavior
When I clone the application, I can run `make build` and build all the `.so` files

### Observed behavior
I get the following stack trace
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/maltz/Documents/workspace/bugsnag-android-ndk/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating root project 'bugsnag-android-ndk'.
> Unable to generate signature for '/Users/maltz/Documents/workspace/bugsnag-android-ndk/ndk/build/outputs/aar/ndk-release.aar' as no signatory is available to sign

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
make: *** [build] Error 1
```

### Steps to reproduce
Clone repository, run `make build`

### Version
1.1.2

### Additional information
Nope!

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by fractalwrench** [comment]
@maltzj sorry for the delay on this. This is down to the Gradle signing plugin being unable to find signing information. You can find further information [here](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials), but essentially you'll need to generate a key pair and add the following information to `~/.gradle/gradle.properties`:

```
signing.keyId=
signing.password=
signing.secretKeyRingFile=/Users/<user>/.gnupg/secring.gpg
```

I'm leaving this issue open for now as we either need to document this, or only apply the signing plugin when making a release.
